### ISSUE TITLE
EX score duplicated visually when EX leaderboards are active and score was submitted through FA+ mode

### ISSUE THREAD

**Issue by marysiamzawka** [florczakraf/boogie-stats#128]
![obraz](https://github.com/florczakraf/boogie-stats/assets/20336327/3f75dc9e-8afe-4567-9fa4-e3898724638c)

Currently when the EX leaderboards are active, they will obviously show you the EX score.
Small issue is that in case of a score submitted with an "FA+" appendix (FA+ mode or otherwise), the EX score will also be visible in the comment field, effectively duplicating it for the website viewer.

This could theoretically be resolved by possibly removing the EX score from the comment while serving the page `FA\+,\s[0-9]*\.[0-9]+EX,\s`, or replacing the commented EX score with money score (kinda redundant when you can get the money score by hovering over the actual score value).

**Comment by florczakraf** [comment]
I'd rather remove the comments completely since they don't have any other useful information. Judgment breakdown could be generated from the data we reliably receive via api instead of theme-based arbitrary comments

**Comment by florczakraf** [comment]
\+ the new comments (at least the ones generated by zmod) don't include misses :(
