### ISSUE TITLE
Have link for current day plays of player.

### ISSUE THREAD

**Issue by Lisek573** [florczakraf/boogie-stats#171]
So usually when I play I tend to have boogie on my phone. After I'm done with session I usually leave the site running in browser. So for example I have played session on 13th April. Now my phone displays https://boogiestats.andr.host/players/9/day/2024-04-13 . To get to current day listing I have to either manually edit the link or click on my player name -> scroll the calendar -> click on current box.

What I would suggest is to make a link, for example https://boogiestats.andr.host/players/9/day/today
which would redirect to site according to current day (so for example today -> 2024-04-14).

**Comment by florczakraf** [comment]
Would you rather have it stay at such `/today` address or redirect to the current day page? The first option would work better if you just wanted to refresh the page, but the second sounds more natural to me.

I also don't see a good place to put such link in the UI. We could make it a hidden thing I guess. There's already the hidden `stats` page: https://boogiestats.andr.host/players/9/stats

**Comment by Lisek573** [comment]
Either option would work if I would just pin the link on my phone and just click it. 

Hidden is fine or put it under calendard on player profile page.
