### ISSUE TITLE
Navbar occludes contents for anchor links

### ISSUE THREAD

**Issue by florczakraf** [florczakraf/boogie-stats#184]
Example: https://boogiestats.andr.host/manual/#locating-game-settings scrolls to:

![image](https://github.com/florczakraf/boogie-stats/assets/9034451/23806ac2-3837-4ca5-a9e8-a6c39da7d424)

Expected:

![image](https://github.com/florczakraf/boogie-stats/assets/9034451/b8dd75e9-9c55-417a-b136-58a57eea975b)

I wonder if it's related to changes from #167 or was it that way since the start

**Comment by KyRZy** [comment]
try adding `html { scroll-padding-top: 60px; }` to the css file
