### ISSUE TITLE
Add player's bio

### ISSUE THREAD

**Issue by florczakraf** [florczakraf/boogie-stats#29]
zibson suggested that it might be useful to let people add and display links to their accounts such as yt, twitch or discord

Lisek requested avatars, afaik there's no GS api that would provide an avatar link so we could just add local ones.

**Comment by florczakraf** [comment]
I don't really like the idea of storing the avatars locally. Perhaps it could be taken from one of the external accounts?

**Comment by florczakraf** [comment]
We could also add an option to check linked livestreaming services status and display information on the main page when someone is live

**Comment by axor-mst** [comment]
> afaik there's no GS api that would provide an avatar link so we could just add local ones.
ITL/SRPG APIs provide that but you need to have player's event ID which is different from GS ID

**Comment by axor-mst** [comment]
Along with what's already prepared in #205 we could also add links for [Tachi](https://github.com/zkrising/Tachi):
- Kamaitachi: ```https://kamai.tachi.ac/u/``` followed by a username
- Bokutachi: ```https://boku.tachi.ac/u/``` followed by a username
- SVG icon: https://raw.githubusercontent.com/zkrising/Tachi/7ba1e125926f6bb078babb89f13f8a5d495863f7/server/example/default-cdn-contents/logos/logo.svg
