### ISSUE TITLE
we need an icon/logo

### ISSUE THREAD

**Issue by florczakraf** [florczakraf/boogie-stats#32]
![image](https://user-images.githubusercontent.com/9034451/194773521-59b3bbfa-2791-41c1-b4db-08ab04728153.png)
 :(

**Comment by Horsey-** [comment]
I’d be interested in helping. Can you give me a bit of inspiration? Colors?

**Comment by florczakraf** [comment]
Thanks for taking an interest! However, some friends are already working on this off-github. I will assign myself to this task to avoid confusion
