### ISSUE TITLE
Sort players/songs by # of quads achieved

### ISSUE THREAD

**Issue by marysiamzawka** [florczakraf/boogie-stats#45]
Add an option to sort players or songs by the amount of 100% scores achieved
Doesn't really matter with the amount and type of scores present on prod, but could be useful for bookkeeping down the line

**Comment by florczakraf** [comment]
this could be extended to other stars as well. I'd probably see it done using new fields on player to keep track of stars for performance reasons (this would also speed up player's page).

The updating logic can a bit tricky, but we have everything we need available during score creation. We already update the player there with a reference to the most recent score so the number of ops will not change.
